In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

In [2]:
df = pd.read_csv(r"D:\Aadesh\MSC\Trimester3\ML-2\CarbonEmissionIndia.csv") #load the dataset

In [3]:
df.head()

States  per capita CO2 (kg per person)  \
0  Andhra Pradesh                          974.17   
1       Arunachal                          405.90   
2           Assam                          340.91   
3           Bihar                          179.01   
4     Chattisgarh                         1963.88   

   per capita CO (kg per person)  per capita CH4 (kg per person)  
0                          27.18                           16.97  
1                          17.43                           25.82  
2                          16.63                           21.29  
3                           8.83                            9.59  
4                          17.56                           22.37

In [4]:
df.shape

(28, 4)

In [6]:
#convert data into an array
X = df.values[:, 1:df.shape[1]]

# 2 clusters

In [7]:
kmeans=KMeans(n_clusters=2, random_state=0).fit(X)
kmeans.labels_

array([0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0])

In [8]:
kmeans.cluster_centers_

array([[ 639.41047619,   17.2652381 ,   15.31952381],
       [1659.37285714,   21.37714286,   20.23857143]])

# 3 clusters

In [11]:
kmeans1=KMeans(n_clusters=3, random_state=0).fit(X)
kmeans1.labels_

array([0, 2, 2, 2, 1, 1, 0, 0, 2, 2, 0, 0, 2, 2, 0, 2, 2, 2, 0, 2, 0, 2,
       2, 0, 2, 2, 2, 2])

In [12]:
kmeans1.cluster_centers_

array([[1197.18333333,   23.47222222,   17.89444444],
       [2313.195     ,   20.34      ,   14.995     ],
       [ 567.18764706,   15.31058824,   16.02      ]])

# 4 clusters

In [13]:
kmeans2=KMeans(n_clusters=4, random_state=0).fit(X)
kmeans2.labels_

array([3, 0, 0, 0, 2, 2, 1, 1, 3, 0, 1, 3, 3, 3, 3, 0, 3, 3, 1, 3, 1, 3,
       3, 3, 0, 0, 0, 3])

In [14]:
kmeans2.cluster_centers_

array([[ 375.87      ,   14.215     ,   17.9725    ],
       [1397.844     ,   21.792     ,   22.336     ],
       [2313.195     ,   20.34      ,   14.995     ],
       [ 801.58923077,   19.14230769,   13.68692308]])

# 5 clusters

In [15]:
kmeans3=KMeans(n_clusters=5, random_state=0).fit(X)
kmeans3.labels_

array([0, 3, 3, 3, 1, 2, 4, 4, 0, 3, 4, 0, 0, 0, 0, 3, 0, 0, 4, 0, 1, 0,
       0, 0, 3, 3, 3, 0])

In [16]:
kmeans3.cluster_centers_

array([[ 801.58923077,   19.14230769,   13.68692308],
       [1790.98      ,   22.73      ,   27.875     ],
       [2662.51      ,   23.12      ,    7.62      ],
       [ 375.87      ,   14.215     ,   17.9725    ],
       [1342.785     ,   20.265     ,   19.575     ]])