In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

In [2]:
#load data into a DataFrame
data=pd.read_csv(r"D:\Aadesh\MSC\Trimester3\ML-2\dailykos.csv")

In [3]:
data.head()

abandon  abc  ability  abortion  absolute  abstain  abu  abuse  accept  \
0        0    0        0         0         0        0    0      0       0   
1        0    0        0         0         0        0    0      0       0   
2        0    0        0         0         0        1    0      0       0   
3        0    0        0         0         0        0    0      0       0   
4        0    0        0         0         0        0    0      0       0   

   access  ...  yeah  year  yesterday  york  youll  young  youre  youve  \
0       0  ...     0     0          0     0      0      0      0      0   
1       0  ...     0     0          0     0      0      0      0      0   
2       0  ...     0     0          0     0      0      0      0      0   
3       0  ...     0     0          2     0      0      1      0      0   
4       0  ...     0     1          1     0      0      1      0      0   

   zogby  zone  
0      0     1  
1      0     0  
2      0     0  
3      0     0  
4      0     0  

[5 rows x 1545 columns]

In [4]:
data.shape

(3430, 1545)

In [5]:
#convert data into an array
X = data.values[:, 0:data.shape[1]]

In [6]:
X

array([[0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

# K=2

In [11]:
kmeans=KMeans(n_clusters=2, random_state=0).fit(X)
kmeans.labels_

array([1, 1, 0, ..., 1, 1, 1])

In [12]:
kmeans.cluster_centers_

array([[0.0147929 , 0.03846154, 0.01775148, ..., 0.02071006, 0.43786982,
        0.01775148],
       [0.02102199, 0.03428202, 0.0339586 , ..., 0.03492885, 0.08408797,
        0.01778784]])

# K=3

In [13]:
kmeans1=KMeans(n_clusters=3, random_state=0).fit(X)
kmeans1.labels_

array([2, 2, 1, ..., 2, 2, 2])

In [14]:
kmeans1.cluster_centers_

array([[0.04140127, 0.05414013, 0.06210191, ..., 0.05414013, 0.20700637,
        0.01910828],
       [0.01510574, 0.03927492, 0.01812689, ..., 0.02114804, 0.44712991,
        0.01812689],
       [0.01578308, 0.029138  , 0.02670983, ..., 0.02994739, 0.05261028,
        0.01740186]])

# K=4

In [15]:
kmeans2=KMeans(n_clusters=4, random_state=0).fit(X)
kmeans2.labels_

array([2, 2, 0, ..., 2, 2, 2])

In [16]:
kmeans2.cluster_centers_

array([[0.01510574, 0.03927492, 0.01812689, ..., 0.02114804, 0.44712991,
        0.01812689],
       [0.05762712, 0.03728814, 0.07457627, ..., 0.04745763, 0.24745763,
        0.01016949],
       [0.01413882, 0.02699229, 0.02485004, ..., 0.02956298, 0.05055698,
        0.01713796],
       [0.03191489, 0.06808511, 0.05319149, ..., 0.05319149, 0.14680851,
        0.02553191]])